name: Improved IPA Build

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
  workflow_dispatch:

env:
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0
  PYTHON_VERSION: 3.11.9
  FLUTTER_VERSION: 3.24.0

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 60

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Cache Python dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Setup Flutter ${{ env.FLUTTER_VERSION }}
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}

    - name: Cache Flutter dependencies
      uses: actions/cache@v3
      with:
        path: ${{ env.FLUTTER_HOME }}/.pub-cache
        key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
        restore-keys: |
          ${{ runner.os }}-pub-

    - name: Install Flet
      run: pip install flet
      
    - name: Verify Flet installation
      run: flet --version

    - name: Flutter doctor
      run: flutter doctor -v

    - name: Prepare build environment
      run: |
        flutter pub get
        flutter clean

    - name: Build IPA (Step 1 - Project creation)
      run: flet create myapp

    - name: Build IPA (Step 2 - Flet build)
      working-directory: ./myapp
      run: |
        flutter config --no-analytics
        flutter pub get
        flutter clean
        flet build ipa --verbose --build-number=$BUILD_NUMBER --build-version=$BUILD_VERSION --include-packages flet_audio
      
    - name: Check build output
      working-directory: ./myapp
      run: |
        ls -R build/ios/ipa
        echo "Build completed. Checking for IPA file..."
        find . -name "*.ipa"

    - name: Upload IPA Artifact
      uses: actions/upload-artifact@v4.3.4
      with:
        name: ipa-build-artifact
        path: myapp/build/ios/ipa
        if-no-files-found: error
        overwrite: true

    - name: Debug info if build fails
      if: failure()
      run: |
        echo "Build failed. Gathering debug information..."
        flutter doctor -v
        pip list
        ls -R
        df -h
